name: Package

on:
  push:
    paths:
      - 'bin/stubload.sh'
      - 'etc/completion.sh'
      - 'etc/stubload.conf'
      - 'build.sh'
      - '.github/workflows/make-pkg.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run build script
      run: |
        BUILD="https://raw.githubusercontent.com/9Omori/stubload/main/build.sh"
        VERSION="0.1.3"
        FULL_VERSION="0.1.3-7"

        curl -Ls -o- $BUILD | sudo PWD=$HOME bash
        sudo mv ~/work/stubload/stubload/build/out ~/out

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ~/out
