name: Debian package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup DEB structure
      run: |
        mkdir ~/deb
      
    - name: Clone repository
      run: |
        cd ~/deb
        git clone https://github.com/9Omori/stubload.git source/

    - name: Setup DEB environment
      run: |
        mkdir ~/deb/build
        cd ~/deb/build
        mkdir -p usr/bin etc/efistub usr/share/bash-completion/completions
        mkdir DEBIAN
        mv ../source/.github/build/deb/control DEBIAN
        mv ../source/bin/stubload.sh usr/bin/stubload
        mv ../source/etc/completion.sh usr/share/bash-completion/completions
        sudo chmod +x usr/bin/stubload
        sudo chown -R root:root etc/efistub
        sudo chmod 700 etc/efistub

    - name: Build DEB package
      run: |
        cd ~/deb/build
        sudo dpkg-deb --root-owner-group --build $(pwd)
        sudo chown $USER ../*.deb
        mv ../*.deb ~

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: deb-out
        path: ~/*.deb
