name: Package

on:
  push:
    paths:
      - 'bin/stubload.sh'
      - 'etc/completion.sh'
      - 'etc/stubload.conf'
      - 'build.sh'
      - '.github/workflows/make-pkg.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run build script
      run: |
        curl -LsO https://raw.githubusercontent.com/9Omori/stubload/main/build.sh
        ./build.sh

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ~/build/out
