name: RedHat package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y rpm
     
    - name: Clone repository
      run: |
        mkdir -p ~/rpmbuild ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        git clone https://github.com/9Omori/stubload.git ~/stubload
  
    - name: Setup RPM build environment
      run: |
        cd ~/rpmbuild
        mkdir stubload-0.1.2
        ln -s stubload-0.1.2 stubload
        mv ~/stubload/stubload.sh ~/stubload/stubload.conf ~/stubload/completion.sh stubload/
        mv ~/stubload/.github/build/rpm/stubload.spec SPECS/
        sudo chmod +x stubload/stubload.sh
        sudo chown -R root:root stubload
        sudo chmod 700 stubload
        sudo tar -czvf SOURCES/stubload-0.1.2.tgz stubload-0.1.2
        exit 0

    - name: Build RPM package
      run: |
        cd ~/rpmbuild
        rpmbuild -bb SPECS/stubload.spec
        mv ~/rpmbuild/RPMS/noarch/*.rpm ~

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: rpm-out
        path: ~/*.rpm
