name: RedHat package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Distrobox
      run: |
        sudo apt install -y podman
        curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

    - name: Create Fedora container
      run: |
        distrobox-create --yes --name fedora --image fedora

    - name: Install dependencies
      run: |
        distrobox-enter fedora -- sudo dnf makecache
        distrobox-enter fedora -- sudo dnf install -y rpmdevtools git
     
    - name: Clone repository
      run: |
        distrobox-enter fedora -- rpmdev-setuptree
        git clone https://github.com/9Omori/stubload.git ~/stubload
  
    - name: Setup RPM build environment
      run: |
        cd ~/rpmbuild
        mkdir stubload-0.1.2
        ln -s stubload-0.1.2 stubload
        mv ~/stubload/stubload.sh ~/stubload/stubload.conf stubload/
        mv ~/stubload/.github/build/rpm/stubload.spec SPECS/
        sudo chmod +x stubload/stubload.sh
        sudo chown -R root:root stubload
        sudo chmod 700 stubload
        sudo tar -czvf SOURCES/stubload-0.1.2.tgz stubload-0.1.2
        exit 0

    - name: Build RPM package
      run: |
        cd ~/rpmbuild
        distrobox-enter fedora -- "rpmbuild -bb SPECS/stubload.spec"
        mv ~/rpmbuild/RPMS/noarch/*.rpm ~

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: rpm-out
        path: ~/*.rpm
