name: Make "rpm" package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: fcos
    steps:
    - name: Install dependencies
      run: |
        sudo dnf makecache
        sudo dnf install -y rpmdevtools

    - name: Setup RPM structure
      run: |
        rpmdev-setuptree
      
    - name: Clone repository
      run: |
        cd ~/rpmbuild
        git clone https://github.com/9Omori/stubload.git ~/stubload
  
    - name: Setup RPM build environment
      run: |
        cd ~/rpmbuild
        mkdir stubload
        mv ~/stubload/stubload.sh ~/stubload/stubload.conf stubload
        mv ~/stubload/.github/build/rpm/stubload.spec SPECS
        chmod +x stubload/stubload.sh
        chown -R root:root stubload
        chmod 700 stubload
        tar -czvf SOURCES/stubload.tgz stubload

    - name: Build RPM package
      run: |
        cd ~/rpmbuild
        rpmbuild -bb SPECS/stubload.spec
        mv ~/rpmbuild/RPMS/noarch/*.rpm ~

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: rpm-out
        path: ~/*.rpm
