name: Package

on:
  push:
    paths:
      - 'bin/stubload.sh'
      - 'etc/completion.sh'
      - 'etc/stubload.conf'
      - 'build.sh'
      - '.github/workflows/make-pkg.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Clone repository
      run: |
        git clone https://github.com/9Omori/stubload.git ~/stubload
        chmod a+x ~/stubload/build.sh
      
    - name: Create structure
      run: |
        cd ~/stubload
        ./build.sh --structure
        ./build.sh --setup_repo
      
    - name: Install dependencies
      run: |
        cd ~/stubload
        ./build.sh --dependencies

    - name: Setup environment
      run: |
        cd ~/stubload
        ./build.sh --environment

    - name: Build packages
      run: |
        cd ~/stubload
        ./build.sh --build_package
        mv ./build/out ~/out

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ~/out
