name: Make "rpm" package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Distrobox
      run: |
        sudo apt update
        sudo add-apt-repository universe
        sudo apt install -y distrobox podman

    - name: Create Fedora container
      run: |
        distrobox-create -Y --name fedora --image fedora

    - name: Install dependencies
      run: |
        distrobox-enter fedora
        sudo dnf makecache
        sudo dnf install -y rpmdevtools git
        exit 0
     
    - name: Clone repository
      run: |
        distrobox-enter fedora
        rpmdev-setuptree
        git clone https://github.com/9Omori/stubload.git ~/stubload
        exit 0
  
    - name: Setup RPM build environment
      run: |
        sudo distrobox-enter fedora
        cd ~/rpmbuild
        mkdir stubload-0.0.1
        ln -s stubload-0.0.1 stubload
        mv ~/stubload/stubload.sh ~/stubload/stubload.conf stubload/
        mv ~/stubload/.github/build/rpm/stubload.spec SPECS/
        sudo chmod +x stubload/stubload.sh
        sudo chown -R root:root stubload
        sudo chmod 700 stubload
        sudo tar -czvf SOURCES/stubload-0.0.1.tgz stubload-0.0.1
        exit 0

    - name: Build RPM package
      run: |
        sudo distrobox-enter fedora
        cd ~/rpmbuild
        rpmbuild -bb SPECS/stubload.spec
        mv ~/rpmbuild/RPMS/noarch/*.rpm ~

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: rpm-out
        path: ~/*.rpm
