name: Package

on:
  push:
    paths:
      - 'bin/stubload.sh'
      - 'etc/completion.sh'
      - 'etc/stubload.conf'
      - '.github/workflows/make-pkg.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: ['0.1.3']
        full-version: ['0.1.3-6']

    runs-on: ubuntu-latest
    steps:

    - name: Setup structure
      run: |
        mkdir -pv \
          ~/deb/build \
          ~/rpmbuild ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} \
          ~/tar

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y rpm git tar zstd zip

    - name: Clone repository
      run: |
        git clone https://github.com/9Omori/stubload.git ~/source
        cd ~/deb
        ln -s ../source .

    - name: Setup environment
      run: |
        cd ~/deb/build

        mkdir -pv \
          DEBIAN \
          usr/bin \
          etc/efistub \
          usr/share/bash-completions/completions \
          lib/stubload/scripts

        mv -v ~/source/.github/build/deb/control DEBIAN/control
        cp -v ~/source/bin/stubload.sh usr/bin/stubload
        cp -v ~/source/etc/completion.sh usr/share/bash-completions/completions/stubload

        sudo chmod +x usr/bin/stubload
        sudo chown -R root:root etc/efistub
        sudo chmod 700 etc/efistub

        cd ~/rpmbuild
        
        mkdir -v stubload-${{ matrix.version }}
        ln -s stubload-${{ matrix.version }} stubload
        mv -v ~/source/.github/build/rpm/stubload.spec SPECS/
        cp -v ~/source/bin/stubload.sh ~/source/etc/completion.sh stubload/
        
        sudo chmod +x stubload/stubload.sh
        sudo chown -R root:root stubload
        sudo chmod 700 stubload

        sudo tar -czvf SOURCES/stubload-${{ matrix.version }}.tgz stubload-${{ matrix.version }}

        cd ~/tar

        mkdir -pv \
          usr/bin \
          etc/efistub \
          usr/share/bash-completion/completions \
          lib/stubload/scripts
        
        cp -v ~/source/bin/stubload.sh usr/bin/stubload
        cp -v ~/source/etc/completion.sh usr/share/bash-completion/completions/stubload

        sudo chmod +x usr/bin/stubload
        sudo chown -R root:root etc/efistub
        sudo chmod 700 etc/efistub
        
        rm -rfv $(ls -A | sed 's/usr//; s/etc//')

    - name: Build package
      run: |
        cd ~/deb/build
        sudo dpkg-deb --root-owner-group --build $(pwd)
        sudo chown $USER ../*.deb
        mv -v ../*.deb ~/stubload-${{ matrix.full-version }}.allarch.deb

        cd ~/rpmbuild
        rpmbuild -bb SPECS/stubload.spec
        mv -v RPMS/noarch/*.rpm ~/stubload-${{ matrix.full-version }}.allarch.tzst

        cd ~/tar
        sudo tar --zstd -cvf stubload.tzst *
        sudo mv *.tzst ~/stubload-${{ matrix.full-version }}.allarch.tzst

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: out
        path: ~/*.rpm ~/*.deb ~/*.tzst
